In [87]:
from sklearn.mixture import GaussianMixture 
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
from numpy import genfromtxt
from sklearn.preprocessing import MinMaxScaler
#my_data = genfromtxt('my_file.csv', delimiter=',')
min_max_scaler = MinMaxScaler()

def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

In [102]:
data= pd.read_csv('final.txt')
df =pd.DataFrame(data= data)
clean_dataset(df)
X1=df.drop(['a', 'b', 'c', 'd', 'g'], axis=1)
X_= X1.values
#feature= np.column_stack((angle, crd))
#X_= min_max_scaler.fit_transform(feature)
print(X_)

[[  2.      101.339    -2.53727 ...  -2.53727  -3.2931   -4.19683]
 [  5.      106.639    -3.82964 ...  -3.82964  -3.25307  -6.7346 ]
 [  5.      106.788    -3.17223 ...  -3.17223  -1.773    -7.21601]
 ...
 [  5.      105.926    -3.10165 ...  -3.10165  -1.97665  -5.73323]
 [  5.      105.298    -3.63633 ...  -3.63633  -1.4206   -6.17347]
 [  5.      105.742    -2.39812 ...  -2.39812  -1.99233  -4.31488]]


In [103]:
clf= GaussianMixture(4,max_iter=500).fit(X_)
clf.fit_predict(X_)

array([2, 0, 0, ..., 0, 0, 0])

In [114]:
value=(clf.fit_predict(X_))


In [105]:
X1= np.column_stack((df,value))

In [106]:
np.savetxt('test.out', X1, delimiter=' ')

In [122]:
crd=X_[:,0]
print(crd)

[2. 5. 5. ... 5. 5. 5.]
